version: "3.10"

services:
  auth-api:
    build: .
    container_name: auth-api
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: us-east-1
      COGNITO_APP_CLIENT_ID: "296unjdo8l02av4neefc9mo0tl"
    networks:
      - backend

  revenda-api:
    build: .
    container_name: revenda-api
    ports:
      - "8001:8001"
    networks:
      - backend
    depends_on:
      - auth-api

networks:
  backend:
    driver: bridge
